import type { Dimension } from "./types";

/** Real code snippets per language × dimension, ~15 lines each */
export const BATTLE_CODE: Record<string, Record<Dimension, string[]>> = {
  Assembly: {
    speed: [
      "section .text",
      "global _fast_sum",
      "_fast_sum:",
      "  push  rbp",
      "  mov   rbp, rsp",
      "  xor   rax, rax",
      "  mov   rcx, rdi          ; count",
      "  mov   rsi, rsi          ; *data",
      ".loop:",
      "  add   rax, [rsi]",
      "  add   rsi, 8",
      "  dec   rcx",
      "  jnz   .loop",
      "  pop   rbp",
      "  ret",
    ],
    security: [
      "section .text",
      "global _stack_guard",
      "_stack_guard:",
      "  push  rbp",
      "  mov   rbp, rsp",
      "  sub   rsp, 256",
      "  mov   rax, [fs:0x28]    ; canary",
      "  mov   [rbp-8], rax",
      "  ; ... user code ...",
      "  mov   rax, [rbp-8]",
      "  xor   rax, [fs:0x28]",
      "  jnz   .stack_smash",
      "  leave",
      "  ret",
      ".stack_smash:",
      "  call  __stack_chk_fail",
    ],
    ecosystem: [
      "section .data",
      "  fmt: db \"Result: %d\", 10, 0",
      "",
      "section .text",
      "extern printf",
      "extern malloc",
      "extern free",
      "extern memcpy",
      "extern strlen",
      "extern strcmp",
      "extern qsort",
      "extern bsearch",
      "global _start",
      "_start:",
      "  ; link against libc.so.6",
      "  ; ld -lc -dynamic-linker",
    ],
    scalability: [
      "section .text",
      "global _spinlock_acquire",
      "_spinlock_acquire:",
      "  mov   eax, 1",
      ".retry:",
      "  xor   ecx, ecx",
      "  lock cmpxchg [rdi], eax",
      "  jnz   .spin",
      "  ret                     ; acquired",
      ".spin:",
      "  pause                   ; hint CPU",
      "  mov   eax, [rdi]",
      "  test  eax, eax",
      "  jnz   .spin",
      "  jmp   .retry",
    ],
    devExp: [
      "; ================================",
      "; TODO: this needs documentation",
      "; Written at 3am, works somehow",
      "; ================================",
      "mov   eax, 0x45        ; magic",
      "shl   eax, 3           ; why 3?",
      "add   eax, [rbx+rcx*4] ; offset",
      "xor   edx, edx         ; clear",
      "div   ecx              ; pray",
      "; FIXME: div by zero when rcx=0",
      "; HACK: caller ensures rcx != 0",
      "mov   [rdi], eax       ; store",
      "ret                    ; good luck",
      "; Last edited: 6 months ago",
      "; Author: \"the intern\"",
    ],
  },

  C: {
    speed: [
      "#include <immintrin.h>",
      "#include <string.h>",
      "",
      "void fast_copy(void *dst, const void *src,",
      "               size_t n) {",
      "  void *buf = mmap(NULL, n,",
      "    PROT_READ | PROT_WRITE,",
      "    MAP_PRIVATE | MAP_ANON, -1, 0);",
      "  if (buf == MAP_FAILED) abort();",
      "",
      "  __m256i *d = (__m256i *)buf;",
      "  const __m256i *s = (const __m256i *)src;",
      "  size_t chunks = n / 32;",
      "  for (size_t i = 0; i < chunks; i++)",
      "    _mm256_store_si256(d + i,",
      "      _mm256_load_si256(s + i));",
      "  memcpy(dst, buf, n);",
      "  munmap(buf, n);",
      "}",
    ],
    security: [
      "#include <stdlib.h>",
      "#include <string.h>",
      "#include <errno.h>",
      "",
      "int secure_copy(char *dst, size_t dst_sz,",
      "                const char *src, size_t n) {",
      "  if (!dst || !src) return -EINVAL;",
      "  if (n > dst_sz) {",
      "    memset(dst, 0, dst_sz);",
      "    return -EOVERFLOW;",
      "  }",
      "  if (n > SIZE_MAX / 2) return -ERANGE;",
      "",
      "  memcpy_s(dst, dst_sz, src, n);",
      "  dst[n] = '\\0';",
      "  return 0;",
      "}",
    ],
    ecosystem: [
      "#include <stdio.h>",
      "#include <stdlib.h>",
      "#include <string.h>",
      "#include <openssl/ssl.h>",
      "#include <openssl/err.h>",
      "#include <curl/curl.h>",
      "#include <sqlite3.h>",
      "#include <pthread.h>",
      "#include <sys/socket.h>",
      "#include <netinet/in.h>",
      "#include <arpa/inet.h>",
      "#include <zlib.h>",
      "#include <jansson.h>",
      "#include <math.h>",
      "#include <signal.h>",
      "// 50+ years of ecosystem",
    ],
    scalability: [
      "#include <pthread.h>",
      "#include <stdatomic.h>",
      "",
      "typedef struct {",
      "  void *(*fn)(void *);",
      "  void *arg;",
      "} task_t;",
      "",
      "static atomic_int active = 0;",
      "",
      "void *worker(void *arg) {",
      "  task_t *t = (task_t *)arg;",
      "  atomic_fetch_add(&active, 1);",
      "  void *res = t->fn(t->arg);",
      "  atomic_fetch_sub(&active, 1);",
      "  return res;",
      "}",
    ],
    devExp: [
      "/* Why does this segfault? */",
      "/* Last 3 people who touched this quit */",
      "",
      "void *ptr = malloc(sizeof(node_t));",
      "if (!ptr) { /* TODO: handle OOM */ }",
      "memset(ptr, 0, sizeof(node_t));",
      "",
      "// Debug: print every pointer",
      "printf(\"ptr=%p val=%d\\n\", ptr, *(int*)ptr);",
      "",
      "free(ptr);",
      "// ptr = NULL; // somebody forgot",
      "printf(\"%d\\n\", *(int*)ptr); // UAF bug",
      "",
      "// Run: valgrind --leak-check=full ./a.out",
      "// Output: 847 errors from 12 contexts",
    ],
  },

  Rust: {
    speed: [
      "use rayon::prelude::*;",
      "use std::simd::*;",
      "",
      "pub fn parallel_transform(data: &[f64])",
      "  -> Vec<f64> {",
      "  data.par_chunks(1024)",
      "    .flat_map(|chunk| {",
      "      chunk.chunks(8).map(|lane| {",
      "        let v = f64x8::from_slice(lane);",
      "        let sq = v * v;",
      "        let result = sq.sqrt();",
      "        result.to_array()",
      "      })",
      "      .flatten()",
      "      .collect::<Vec<_>>()",
      "    })",
      "    .collect()",
      "}",
    ],
    security: [
      "use std::num::NonZeroU64;",
      "",
      "#[derive(Debug)]",
      "pub struct SafeBuffer {",
      "  data: Vec<u8>,",
      "  checksum: u64,",
      "}",
      "",
      "impl SafeBuffer {",
      "  pub fn new(data: Vec<u8>) -> Self {",
      "    let checksum = Self::compute_hash(&data);",
      "    Self { data, checksum }",
      "  }",
      "",
      "  pub fn verify(&self) -> Result<&[u8], Error> {",
      "    if Self::compute_hash(&self.data)",
      "      != self.checksum {",
      "      return Err(Error::IntegrityFail);",
      "    }",
      "    Ok(&self.data)",
      "  }",
      "}",
    ],
    ecosystem: [
      "use tokio::runtime::Runtime;",
      "use axum::{Router, routing::get};",
      "use sqlx::postgres::PgPoolOptions;",
      "use serde::{Serialize, Deserialize};",
      "use tracing::{info, instrument};",
      "use tower_http::cors::CorsLayer;",
      "use reqwest::Client;",
      "use redis::AsyncCommands;",
      "use uuid::Uuid;",
      "use chrono::{DateTime, Utc};",
      "use anyhow::Result;",
      "use clap::Parser;",
      "use thiserror::Error;",
      "use dotenvy::dotenv;",
      "// cargo.toml: 23 dependencies",
      "// all compile-time checked",
    ],
    scalability: [
      "use tokio::sync::mpsc;",
      "use tokio::task::JoinSet;",
      "",
      "pub async fn process_pipeline(",
      "  data: Vec<Chunk>,",
      ") -> Vec<Output> {",
      "  let (tx, mut rx) = mpsc::channel(256);",
      "  let mut set = JoinSet::new();",
      "",
      "  for chunk in data {",
      "    let tx = tx.clone();",
      "    set.spawn(async move {",
      "      let result = transform(chunk).await;",
      "      tx.send(result).await.unwrap();",
      "    });",
      "  }",
      "  drop(tx);",
      "",
      "  let mut results = Vec::new();",
      "  while let Some(r) = rx.recv().await {",
      "    results.push(r);",
      "  }",
      "  results",
      "}",
    ],
    devExp: [
      "#[derive(Debug, Clone, Serialize)]",
      "#[derive(Deserialize, PartialEq)]",
      "pub struct Config {",
      "  pub host: String,",
      "  pub port: u16,",
      "  pub db_url: String,",
      "  pub max_conns: u32,",
      "}",
      "",
      "impl Config {",
      "  /// Load from env with validation",
      "  pub fn from_env() -> Result<Self> {",
      "    dotenvy::dotenv().ok();",
      "    Ok(Self {",
      "      host: env::var(\"HOST\")?,",
      "      port: env::var(\"PORT\")?.parse()?,",
      "      db_url: env::var(\"DATABASE_URL\")?,",
      "      max_conns: 10,",
      "    })",
      "  }",
      "}",
    ],
  },

  Java: {
    speed: [
      "import java.util.stream.*;",
      "import java.util.concurrent.*;",
      "",
      "public class FastProcessor {",
      "  private final ForkJoinPool pool =",
      "    new ForkJoinPool(Runtime.getRuntime()",
      "      .availableProcessors());",
      "",
      "  public long parallelSum(int[] data) {",
      "    return pool.submit(() ->",
      "      IntStream.of(data)",
      "        .parallel()",
      "        .mapToLong(x -> (long) x * x)",
      "        .sum()",
      "    ).join();",
      "  }",
      "}",
    ],
    security: [
      "import javax.crypto.*;",
      "import java.security.*;",
      "",
      "@Service",
      "public class AuthService {",
      "  @Autowired",
      "  private final KeyStore vault;",
      "",
      "  @Secured(\"ROLE_ADMIN\")",
      "  public boolean verify(String token) {",
      "    try {",
      "      Key key = vault.getKey(\"hmac\", pwd);",
      "      Mac mac = Mac.getInstance(\"HmacSHA256\");",
      "      mac.init(key);",
      "      byte[] sig = mac.doFinal(payload);",
      "      return MessageDigest.isEqual(sig, expected);",
      "    } catch (Exception e) {",
      "      log.error(\"Auth failed\", e);",
      "      return false;",
      "    }",
      "  }",
      "}",
    ],
    ecosystem: [
      "import org.springframework.boot.*;",
      "import org.springframework.web.bind.*;",
      "import org.hibernate.annotations.*;",
      "import org.apache.kafka.clients.*;",
      "import io.micrometer.core.instrument.*;",
      "import com.fasterxml.jackson.databind.*;",
      "import org.slf4j.Logger;",
      "import lombok.*;",
      "import reactor.core.publisher.Flux;",
      "import io.grpc.ManagedChannel;",
      "import org.elasticsearch.client.*;",
      "import com.google.guava.collect.*;",
      "",
      "@SpringBootApplication",
      "@EnableAutoConfiguration",
      "@EnableKafka",
      "public class Application { }",
    ],
    scalability: [
      "import java.util.concurrent.*;",
      "",
      "public class WorkStealingEngine {",
      "  private final ExecutorService pool =",
      "    Executors.newWorkStealingPool();",
      "  private final Semaphore throttle =",
      "    new Semaphore(1000);",
      "",
      "  public <T> CompletableFuture<List<T>>",
      "    scatter(List<Callable<T>> tasks) {",
      "    List<CompletableFuture<T>> futures =",
      "      tasks.stream().map(t ->",
      "        CompletableFuture.supplyAsync(() -> {",
      "          throttle.acquireUninterruptibly();",
      "          try { return t.call(); }",
      "          catch (Exception e) { throw new",
      "            RuntimeException(e); }",
      "          finally { throttle.release(); }",
      "        }, pool)",
      "      ).toList();",
      "    return CompletableFuture.allOf(",
      "      futures.toArray(new CompletableFuture[0]))",
      "      .thenApply(v -> futures.stream()",
      "        .map(CompletableFuture::join).toList());",
      "  }",
      "}",
    ],
    devExp: [
      "@Data @Builder",
      "@NoArgsConstructor",
      "@AllArgsConstructor",
      "@Entity @Table(name = \"users\")",
      "public class User {",
      "  @Id @GeneratedValue",
      "  private UUID id;",
      "",
      "  @Column(nullable = false)",
      "  private String username;",
      "",
      "  @Email @NotBlank",
      "  private String email;",
      "",
      "  @JsonIgnore",
      "  private String passwordHash;",
      "",
      "  @CreatedDate",
      "  private Instant createdAt;",
      "}",
    ],
  },

  Go: {
    speed: [
      "package compute",
      "",
      "import (",
      "  \"runtime\"",
      "  \"sync\"",
      ")",
      "",
      "func ParallelSum(data []int64) int64 {",
      "  n := runtime.NumCPU()",
      "  ch := make(chan int64, n)",
      "  chunk := len(data) / n",
      "",
      "  for i := 0; i < n; i++ {",
      "    go func(start, end int) {",
      "      var s int64",
      "      for _, v := range data[start:end] {",
      "        s += v * v",
      "      }",
      "      ch <- s",
      "    }(i*chunk, min((i+1)*chunk, len(data)))",
      "  }",
      "",
      "  var total int64",
      "  for i := 0; i < n; i++ {",
      "    total += <-ch",
      "  }",
      "  return total",
      "}",
    ],
    security: [
      "package auth",
      "",
      "import (",
      "  \"crypto/hmac\"",
      "  \"crypto/sha256\"",
      "  \"crypto/subtle\"",
      "  \"errors\"",
      ")",
      "",
      "var ErrInvalidSig = errors.New(\"invalid sig\")",
      "",
      "func Verify(payload, sig, key []byte) error {",
      "  mac := hmac.New(sha256.New, key)",
      "  mac.Write(payload)",
      "  expected := mac.Sum(nil)",
      "  if subtle.ConstantTimeCompare(",
      "    expected, sig) != 1 {",
      "    return ErrInvalidSig",
      "  }",
      "  return nil",
      "}",
    ],
    ecosystem: [
      "package main",
      "",
      "import (",
      "  \"net/http\"",
      "  \"encoding/json\"",
      "  \"database/sql\"",
      "  \"context\"",
      "  \"log/slog\"",
      "  \"os\"",
      "  \"os/signal\"",
      "  \"time\"",
      "  _ \"github.com/lib/pq\"",
      "  \"github.com/go-chi/chi/v5\"",
      "  \"github.com/redis/go-redis/v9\"",
      "  \"go.opentelemetry.io/otel\"",
      ")",
      "// go.sum: 42 packages, all stdlib-style",
    ],
    scalability: [
      "package pipeline",
      "",
      "import \"sync\"",
      "",
      "func FanOut[T, R any](",
      "  input []T,",
      "  workers int,",
      "  fn func(T) R,",
      ") []R {",
      "  ch := make(chan T, len(input))",
      "  results := make([]R, len(input))",
      "  var wg sync.WaitGroup",
      "",
      "  for w := 0; w < workers; w++ {",
      "    wg.Add(1)",
      "    go func() {",
      "      defer wg.Done()",
      "      for item := range ch {",
      "        results[indexOf(item)] = fn(item)",
      "      }",
      "    }()",
      "  }",
      "",
      "  for _, item := range input {",
      "    ch <- item",
      "  }",
      "  close(ch)",
      "  wg.Wait()",
      "  return results",
      "}",
    ],
    devExp: [
      "package config",
      "",
      "import (",
      "  \"encoding/json\"",
      "  \"os\"",
      ")",
      "",
      "type Config struct {",
      "  Host    string `json:\"host\"`",
      "  Port    int    `json:\"port\"`",
      "  DBUrl   string `json:\"db_url\"`",
      "  Workers int    `json:\"workers\"`",
      "}",
      "",
      "func Load(path string) (*Config, error) {",
      "  f, err := os.Open(path)",
      "  if err != nil { return nil, err }",
      "  defer f.Close()",
      "  var cfg Config",
      "  json.NewDecoder(f).Decode(&cfg)",
      "  return &cfg, nil",
      "} // 21 lines. Ship it.",
    ],
  },

  JavaScript: {
    speed: [
      "// High-performance async pipeline",
      "const CONCURRENCY = navigator.hardwareConcurrency;",
      "",
      "async function parallelProcess(urls) {",
      "  const pool = new Array(CONCURRENCY);",
      "  const results = [];",
      "",
      "  for (let i = 0; i < urls.length; i++) {",
      "    const slot = i % CONCURRENCY;",
      "    if (pool[slot]) {",
      "      results.push(await pool[slot]);",
      "    }",
      "    pool[slot] = fetch(urls[i])",
      "      .then(r => r.json())",
      "      .then(data => transform(data));",
      "  }",
      "",
      "  const remaining = await Promise.all(",
      "    pool.filter(Boolean));",
      "  return [...results, ...remaining];",
      "}",
    ],
    security: [
      "import crypto from 'node:crypto';",
      "",
      "class TokenService {",
      "  #secret;",
      "  #algorithm = 'sha256';",
      "",
      "  constructor(secret) {",
      "    this.#secret = secret;",
      "  }",
      "",
      "  sign(payload) {",
      "    const nonce = crypto.randomUUID();",
      "    const hmac = crypto.createHmac(",
      "      this.#algorithm, this.#secret);",
      "    hmac.update(JSON.stringify(payload));",
      "    hmac.update(nonce);",
      "    return { nonce, sig: hmac.digest('hex') };",
      "  }",
      "",
      "  verify(payload, nonce, sig) {",
      "    const hmac = crypto.createHmac(",
      "      this.#algorithm, this.#secret);",
      "    hmac.update(JSON.stringify(payload));",
      "    hmac.update(nonce);",
      "    const expected = hmac.digest('hex');",
      "    return crypto.timingSafeEqual(",
      "      Buffer.from(sig), Buffer.from(expected));",
      "  }",
      "}",
    ],
    ecosystem: [
      "import React from 'react';",
      "import express from 'express';",
      "import next from 'next';",
      "import { PrismaClient } from '@prisma/client';",
      "import Redis from 'ioredis';",
      "import Stripe from 'stripe';",
      "import { S3Client } from '@aws-sdk/client-s3';",
      "import { Server } from 'socket.io';",
      "import dayjs from 'dayjs';",
      "import { z } from 'zod';",
      "import pino from 'pino';",
      "import nodemailer from 'nodemailer';",
      "import sharp from 'sharp';",
      "import Bull from 'bull';",
      "// node_modules: 1,247 packages",
      "// npm audit: 0 vulnerabilities (today)",
    ],
    scalability: [
      "// Worker thread pool for CPU tasks",
      "import { Worker, isMainThread,",
      "  parentPort } from 'node:worker_threads';",
      "",
      "if (!isMainThread) {",
      "  parentPort.on('message', async (data) => {",
      "    const result = heavyCompute(data);",
      "    parentPort.postMessage(result);",
      "  });",
      "} else {",
      "  const pool = Array.from({ length: 8 },",
      "    () => new Worker(import.meta.filename));",
      "",
      "  async function dispatch(data) {",
      "    const worker = pool[nextSlot++ % 8];",
      "    return new Promise((resolve) => {",
      "      worker.once('message', resolve);",
      "      worker.postMessage(data);",
      "    });",
      "  }",
      "}",
    ],
    devExp: [
      "// api/users/route.ts - Next.js 15",
      "import { NextResponse } from 'next/server';",
      "import { prisma } from '@/lib/db';",
      "import { z } from 'zod';",
      "",
      "const schema = z.object({",
      "  name: z.string().min(1),",
      "  email: z.string().email(),",
      "});",
      "",
      "export async function POST(req: Request) {",
      "  const body = schema.parse(await req.json());",
      "  const user = await prisma.user.create({",
      "    data: body,",
      "  });",
      "  return NextResponse.json(user, { status: 201 });",
      "}",
      "// 17 lines: validated, typed, deployed",
    ],
  },

  Python: {
    speed: [
      "import numpy as np",
      "from concurrent.futures import ProcessPoolExecutor",
      "from functools import reduce",
      "",
      "def parallel_transform(data: np.ndarray)",
      "    -> np.ndarray:",
      "  \"\"\"SIMD-optimized via NumPy C backend\"\"\"",
      "  chunks = np.array_split(",
      "    data, mp.cpu_count())",
      "",
      "  with ProcessPoolExecutor() as pool:",
      "    results = list(pool.map(",
      "      lambda c: np.sqrt(c ** 2 + 1),",
      "      chunks",
      "    ))",
      "",
      "  return np.concatenate(results)",
    ],
    security: [
      "import bcrypt",
      "import secrets",
      "from cryptography.fernet import Fernet",
      "",
      "class Vault:",
      "  def __init__(self, master_key: bytes):",
      "    self._cipher = Fernet(master_key)",
      "    self._pepper = secrets.token_bytes(32)",
      "",
      "  def hash_password(self, pwd: str) -> bytes:",
      "    salted = pwd.encode() + self._pepper",
      "    return bcrypt.hashpw(",
      "      salted, bcrypt.gensalt(rounds=14))",
      "",
      "  def verify(self, pwd: str, hashed: bytes)",
      "      -> bool:",
      "    salted = pwd.encode() + self._pepper",
      "    return bcrypt.checkpw(salted, hashed)",
      "",
      "  def encrypt(self, data: bytes) -> bytes:",
      "    return self._cipher.encrypt(data)",
    ],
    ecosystem: [
      "import pandas as pd",
      "import numpy as np",
      "import tensorflow as tf",
      "from fastapi import FastAPI, Depends",
      "from sqlalchemy import create_engine",
      "from pydantic import BaseModel",
      "import redis",
      "import celery",
      "from sklearn.ensemble import RandomForest",
      "import matplotlib.pyplot as plt",
      "import requests",
      "import boto3",
      "import pytest",
      "from loguru import logger",
      "# pip list | wc -l => 847 packages",
      "# ML + Web + Data + DevOps in one lang",
    ],
    scalability: [
      "import asyncio",
      "import aiohttp",
      "from asyncio import Semaphore",
      "",
      "async def fetch_all(",
      "  urls: list[str],",
      "  max_concurrent: int = 50",
      ") -> list[dict]:",
      "  sem = Semaphore(max_concurrent)",
      "  results = []",
      "",
      "  async def fetch(session, url):",
      "    async with sem:",
      "      async with session.get(url) as resp:",
      "        data = await resp.json()",
      "        results.append(data)",
      "",
      "  async with aiohttp.ClientSession() as s:",
      "    tasks = [fetch(s, u) for u in urls]",
      "    await asyncio.gather(*tasks)",
      "",
      "  return results",
    ],
    devExp: [
      "from fastapi import FastAPI",
      "from pydantic import BaseModel",
      "",
      "app = FastAPI()",
      "",
      "class Item(BaseModel):",
      "  name: str",
      "  price: float",
      "  in_stock: bool = True",
      "",
      "@app.get('/items')",
      "async def list_items():",
      "  return await db.fetch_all(items.select())",
      "",
      "@app.post('/items', status_code=201)",
      "async def create(item: Item):",
      "  return await db.execute(",
      "    items.insert().values(**item.dict()))",
      "",
      "# uvicorn app:app --reload",
      "# Auto docs at /docs. That's it.",
    ],
  },

  Solidity: {
    speed: [
      "// SPDX-License-Identifier: MIT",
      "pragma solidity ^0.8.20;",
      "",
      "contract GasOptimized {",
      "  uint256[] private data;",
      "",
      "  function batchSum()",
      "    external view returns (uint256 result) {",
      "    assembly {",
      "      let len := sload(data.slot)",
      "      let ptr := add(data.slot, 0x20)",
      "      for { let i := 0 } lt(i, len)",
      "        { i := add(i, 1) } {",
      "        result := add(result,",
      "          sload(add(ptr, i)))",
      "      }",
      "    }",
      "  }",
      "}",
    ],
    security: [
      "// SPDX-License-Identifier: MIT",
      "pragma solidity ^0.8.20;",
      "",
      "import \"@openzeppelin/contracts/",
      "  security/ReentrancyGuard.sol\";",
      "",
      "contract SecureVault is ReentrancyGuard {",
      "  mapping(address => uint256) balances;",
      "",
      "  function withdraw(uint256 amount)",
      "    external nonReentrant {",
      "    require(balances[msg.sender] >= amount,",
      "      \"INSUFFICIENT_BALANCE\");",
      "    balances[msg.sender] -= amount;",
      "    (bool ok, ) = msg.sender.call{",
      "      value: amount}(\"\");",
      "    require(ok, \"TRANSFER_FAILED\");",
      "    emit Withdrawal(msg.sender, amount);",
      "  }",
      "}",
    ],
    ecosystem: [
      "// SPDX-License-Identifier: MIT",
      "pragma solidity ^0.8.20;",
      "",
      "import \"@openzeppelin/contracts/",
      "  token/ERC721/ERC721.sol\";",
      "import \"@openzeppelin/contracts/",
      "  access/Ownable.sol\";",
      "import \"@openzeppelin/contracts/",
      "  utils/Counters.sol\";",
      "import \"@chainlink/contracts/src/",
      "  v0.8/interfaces/AggregatorV3.sol\";",
      "import \"@uniswap/v3-periphery/",
      "  contracts/interfaces/ISwapRouter.sol\";",
      "import \"@aave/v3-core/contracts/",
      "  interfaces/IPool.sol\";",
      "// DeFi legos: composable by design",
    ],
    scalability: [
      "// SPDX-License-Identifier: MIT",
      "pragma solidity ^0.8.20;",
      "",
      "contract ShardProcessor {",
      "  struct Shard {",
      "    bytes32 root;",
      "    uint64 nonce;",
      "  }",
      "",
      "  function processBatch(",
      "    Shard[] calldata shards",
      "  ) external {",
      "    uint256 len = shards.length;",
      "    for (uint256 i; i < len; ) {",
      "      _verify(shards[i]);",
      "      unchecked { ++i; }",
      "    }",
      "    emit BatchProcessed(len, block.number);",
      "  }",
      "}",
    ],
    devExp: [
      "// SPDX-License-Identifier: MIT",
      "pragma solidity ^0.8.20;",
      "",
      "/// @title CodeWars NFT Collection",
      "/// @author CodeWars Team",
      "/// @notice Mint & trade battle cards",
      "/// @dev Follows ERC721 standard",
      "",
      "interface ICodeWarsNFT {",
      "  /// @notice Mint a new warrior card",
      "  /// @param to Recipient address",
      "  /// @param language Card language ID",
      "  /// @return tokenId The new token ID",
      "  function mint(address to, uint8 language)",
      "    external returns (uint256 tokenId);",
      "",
      "  /// @notice Get card battle stats",
      "  function stats(uint256 tokenId)",
      "    external view returns (Stats memory);",
      "}",
    ],
  },

  CPlusPlus: {
    speed: [
      "#include <algorithm>",
      "#include <execution>",
      "#include <numeric>",
      "#include <vector>",
      "",
      "double parallel_dot(const std::vector<double>& a,",
      "                    const std::vector<double>& b) {",
      "  return std::transform_reduce(",
      "    std::execution::par_unseq,",
      "    a.begin(), a.end(),",
      "    b.begin(),",
      "    0.0,",
      "    std::plus<>{},",
      "    std::multiplies<>{}",
      "  );",
      "}",
    ],
    security: [
      "#include <memory>",
      "#include <span>",
      "#include <optional>",
      "",
      "class SecureBuffer {",
      "  std::unique_ptr<std::byte[]> data_;",
      "  size_t size_;",
      "public:",
      "  explicit SecureBuffer(size_t n)",
      "    : data_(std::make_unique<std::byte[]>(n)),",
      "      size_(n) {}",
      "",
      "  ~SecureBuffer() {",
      "    volatile auto* p = data_.get();",
      "    std::fill_n(p, size_, std::byte{0});",
      "  }",
      "",
      "  std::span<const std::byte> view() const {",
      "    return {data_.get(), size_};",
      "  }",
      "};",
    ],
    ecosystem: [
      "#include <iostream>",
      "#include <vector>",
      "#include <string>",
      "#include <filesystem>",
      "#include <ranges>",
      "#include <format>",
      "#include <thread>",
      "#include <coroutine>",
      "#include <expected>",
      "// Boost libraries",
      "#include <boost/asio.hpp>",
      "#include <boost/beast.hpp>",
      "#include <boost/json.hpp>",
      "// Third-party",
      "#include <spdlog/spdlog.h>",
      "#include <fmt/core.h>",
    ],
    scalability: [
      "#include <thread>",
      "#include <queue>",
      "#include <mutex>",
      "#include <condition_variable>",
      "#include <functional>",
      "",
      "class ThreadPool {",
      "  std::vector<std::jthread> workers_;",
      "  std::queue<std::function<void()>> tasks_;",
      "  std::mutex mtx_;",
      "  std::condition_variable cv_;",
      "public:",
      "  explicit ThreadPool(size_t n) {",
      "    for (size_t i = 0; i < n; ++i)",
      "      workers_.emplace_back([this](std::stop_token st) {",
      "        while (!st.stop_requested()) {",
      "          std::unique_lock lk(mtx_);",
      "          cv_.wait(lk, [&]{ return !tasks_.empty(); });",
      "          auto task = std::move(tasks_.front());",
      "          tasks_.pop();",
      "          lk.unlock();",
      "          task();",
      "        }",
      "      });",
      "  }",
      "};",
    ],
    devExp: [
      "#include <format>",
      "#include <print>",
      "#include <ranges>",
      "#include <vector>",
      "",
      "auto main() -> int {",
      "  auto nums = std::vector{3, 1, 4, 1, 5, 9};",
      "",
      "  auto evens = nums",
      "    | std::views::filter([](int n) {",
      "        return n % 2 == 0; })",
      "    | std::views::transform([](int n) {",
      "        return n * n; });",
      "",
      "  for (auto v : evens)",
      "    std::println(\"val: {}\", v);",
      "}",
    ],
  },

  CSharp: {
    speed: [
      "using System.Numerics;",
      "using System.Runtime.Intrinsics;",
      "using System.Runtime.Intrinsics.X86;",
      "",
      "public static class FastMath {",
      "  public static float SimdDot(",
      "      ReadOnlySpan<float> a,",
      "      ReadOnlySpan<float> b) {",
      "    var sum = Vector256<float>.Zero;",
      "    int i = 0;",
      "    for (; i + 8 <= a.Length; i += 8) {",
      "      var va = Vector256.Create(a.Slice(i, 8));",
      "      var vb = Vector256.Create(b.Slice(i, 8));",
      "      sum = Avx.Add(sum, Avx.Multiply(va, vb));",
      "    }",
      "    return Vector256.Sum(sum);",
      "  }",
      "}",
    ],
    security: [
      "using System.Security.Cryptography;",
      "using Microsoft.AspNetCore.Identity;",
      "",
      "public class AuthService {",
      "  private readonly PasswordHasher<User> _hasher = new();",
      "",
      "  public string HashPassword(User user, string pwd) {",
      "    return _hasher.HashPassword(user, pwd);",
      "  }",
      "",
      "  public bool Verify(User user, string pwd,",
      "                     string hash) {",
      "    var result = _hasher.VerifyHashedPassword(",
      "      user, hash, pwd);",
      "    return result ==",
      "      PasswordVerificationResult.Success;",
      "  }",
      "}",
    ],
    ecosystem: [
      "using Microsoft.AspNetCore.Builder;",
      "using Microsoft.EntityFrameworkCore;",
      "using Microsoft.Extensions.DependencyInjection;",
      "using System.Text.Json;",
      "using Azure.Storage.Blobs;",
      "using StackExchange.Redis;",
      "using MassTransit;",
      "using Serilog;",
      "using AutoMapper;",
      "using FluentValidation;",
      "using MediatR;",
      "using Polly;",
      "using Hangfire;",
      "using SignalR;",
      "// dotnet: enterprise-grade, batteries-included",
    ],
    scalability: [
      "using System.Threading.Channels;",
      "",
      "public class Pipeline<T> {",
      "  private readonly Channel<T> _channel =",
      "    Channel.CreateBounded<T>(1000);",
      "",
      "  public async Task ProduceAsync(",
      "      IEnumerable<T> items,",
      "      CancellationToken ct = default) {",
      "    foreach (var item in items)",
      "      await _channel.Writer.WriteAsync(item, ct);",
      "    _channel.Writer.Complete();",
      "  }",
      "",
      "  public async IAsyncEnumerable<T> ConsumeAsync() {",
      "    await foreach (var item in",
      "      _channel.Reader.ReadAllAsync())",
      "      yield return item;",
      "  }",
      "}",
    ],
    devExp: [
      "// Minimal API - .NET 8",
      "var builder = WebApplication.CreateBuilder(args);",
      "builder.Services.AddDbContext<AppDb>(opt =>",
      "  opt.UseNpgsql(builder.Configuration",
      "    .GetConnectionString(\"Default\")));",
      "",
      "var app = builder.Build();",
      "",
      "app.MapGet(\"/users/{id}\", async (int id,",
      "  AppDb db) => await db.Users.FindAsync(id)",
      "    is User user",
      "    ? Results.Ok(user)",
      "    : Results.NotFound());",
      "",
      "app.MapPost(\"/users\", async (User user,",
      "  AppDb db) => {",
      "  db.Users.Add(user);",
      "  await db.SaveChangesAsync();",
      "  return Results.Created($\"/users/{user.Id}\",",
      "    user);",
      "});",
      "",
      "app.Run();",
    ],
  },

  Clojure: {
    speed: [
      "(ns compute.parallel",
      "  (:require [clojure.core.reducers :as r]))",
      "",
      "(defn parallel-sum [data]",
      "  (r/fold",
      "    512",
      "    +",
      "    (r/map #(* % %) data)))",
      "",
      "(defn pipeline-transform [coll]",
      "  (->> coll",
      "       (pmap #(Math/sqrt (double %)))",
      "       (filterv pos?)",
      "       (reduce +)))",
      "",
      ";; Fork/join under the hood",
      ";; Zero-copy persistent vectors",
    ],
    security: [
      "(ns auth.crypto",
      "  (:require [buddy.hashers :as hashers]",
      "            [buddy.sign.jwt :as jwt]",
      "            [clojure.spec.alpha :as s]))",
      "",
      "(s/def ::password (s/and string?",
      "  #(>= (count %) 12)))",
      "",
      "(defn hash-password [pwd]",
      "  {:pre [(s/valid? ::password pwd)]}",
      "  (hashers/derive pwd {:alg :bcrypt+sha512}))",
      "",
      "(defn verify [pwd hash]",
      "  (hashers/check pwd hash))",
      "",
      "(defn sign-token [claims secret]",
      "  (jwt/sign claims secret {:alg :hs256}))",
    ],
    ecosystem: [
      "(ns app.core",
      "  (:require [ring.adapter.jetty :as jetty]",
      "            [compojure.core :refer :all]",
      "            [compojure.route :as route]",
      "            [next.jdbc :as jdbc]",
      "            [honey.sql :as sql]",
      "            [clojure.data.json :as json]",
      "            [clojure.core.async :as async]",
      "            [mount.core :as mount]",
      "            [taoensso.timbre :as log]",
      "            [clj-http.client :as http]",
      "            [clojure.spec.alpha :as s]",
      "            [integrant.core :as ig]))",
      "",
      ";; Lisp + JVM ecosystem = powerful combo",
    ],
    scalability: [
      "(ns pipeline.async",
      "  (:require [clojure.core.async :as a",
      "             :refer [>! <! go chan pipe]]))",
      "",
      "(defn fan-out [in-ch n work-fn]",
      "  (let [out-ch (chan 256)]",
      "    (dotimes [_ n]",
      "      (go (loop []",
      "        (when-let [item (<! in-ch)]",
      "          (let [result (work-fn item)]",
      "            (>! out-ch result))",
      "          (recur)))))",
      "    out-ch))",
      "",
      "(defn process [items]",
      "  (let [in (chan (count items))]",
      "    (doseq [i items] (a/put! in i))",
      "    (a/close! in)",
      "    (fan-out in 8 transform)))",
    ],
    devExp: [
      "(ns app.api",
      "  (:require [ring.util.response :as resp]",
      "            [next.jdbc :as jdbc]))",
      "",
      "(defn get-users [db]",
      "  (fn [_req]",
      "    (resp/response",
      "      (jdbc/execute! db",
      "        [\"SELECT * FROM users\"]))))",
      "",
      "(defn create-user [db]",
      "  (fn [{:keys [body]}]",
      "    (let [user (jdbc/execute-one! db",
      "            (sql/format {:insert-into :users",
      "                         :values [body]}))]",
      "      (resp/created (str \"/users/\" (:id user))",
      "        user))))",
    ],
  },

  COBOL: {
    speed: [
      "       IDENTIFICATION DIVISION.",
      "       PROGRAM-ID. FAST-BATCH.",
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01 WS-TABLE.",
      "         05 WS-ENTRY OCCURS 10000 TIMES",
      "            INDEXED BY WS-IDX.",
      "           10 WS-AMOUNT   PIC 9(9)V99.",
      "           10 WS-STATUS   PIC X(1).",
      "       01 WS-TOTAL       PIC 9(12)V99.",
      "       PROCEDURE DIVISION.",
      "       MAIN-PARA.",
      "           PERFORM VARYING WS-IDX",
      "             FROM 1 BY 1 UNTIL WS-IDX > 10000",
      "             ADD WS-AMOUNT(WS-IDX) TO WS-TOTAL",
      "           END-PERFORM.",
      "           STOP RUN.",
    ],
    security: [
      "       IDENTIFICATION DIVISION.",
      "       PROGRAM-ID. SECURE-TRANSACTION.",
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01 WS-AUTH-TOKEN   PIC X(64).",
      "       01 WS-ACCT-NUM     PIC 9(10).",
      "       01 WS-PIN          PIC 9(4).",
      "       01 WS-HASH         PIC X(64).",
      "       01 WS-VALID-FLAG   PIC X VALUE 'N'.",
      "       PROCEDURE DIVISION.",
      "       VALIDATE-PARA.",
      "           IF WS-PIN = SPACES OR LOW-VALUES",
      "             MOVE 'N' TO WS-VALID-FLAG",
      "             DISPLAY 'INVALID PIN REJECTED'",
      "             STOP RUN",
      "           END-IF.",
      "           CALL 'HASHPGM' USING WS-PIN WS-HASH.",
      "           MOVE 'Y' TO WS-VALID-FLAG.",
    ],
    ecosystem: [
      "       IDENTIFICATION DIVISION.",
      "       PROGRAM-ID. MAINFRAME-APP.",
      "       ENVIRONMENT DIVISION.",
      "       INPUT-OUTPUT SECTION.",
      "       FILE-CONTROL.",
      "           SELECT TRANS-FILE ASSIGN TO",
      "             'DD:TRANSIN'",
      "             ORGANIZATION IS SEQUENTIAL.",
      "           SELECT REPORT-FILE ASSIGN TO",
      "             'DD:RPTOUT'.",
      "       DATA DIVISION.",
      "       FILE SECTION.",
      "       FD TRANS-FILE.",
      "       01 TRANS-RECORD    PIC X(80).",
      "       PROCEDURE DIVISION.",
      "           OPEN INPUT TRANS-FILE.",
      "      *    CICS, DB2, IMS, JCL, VSAM",
      "      *    60 years of enterprise backbone",
    ],
    scalability: [
      "       IDENTIFICATION DIVISION.",
      "       PROGRAM-ID. BATCH-ENGINE.",
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01 WS-RECORDS-READ  PIC 9(9) VALUE 0.",
      "       01 WS-COMMIT-FREQ   PIC 9(5) VALUE 5000.",
      "       01 WS-RECORD        PIC X(200).",
      "       PROCEDURE DIVISION.",
      "       PROCESS-LOOP.",
      "           PERFORM UNTIL WS-EOF = 'Y'",
      "             READ TRANS-FILE INTO WS-RECORD",
      "               AT END MOVE 'Y' TO WS-EOF",
      "             END-READ",
      "             PERFORM VALIDATE-RECORD",
      "             ADD 1 TO WS-RECORDS-READ",
      "             IF FUNCTION MOD(WS-RECORDS-READ",
      "               WS-COMMIT-FREQ) = 0",
      "               EXEC SQL COMMIT END-EXEC",
      "             END-IF",
      "           END-PERFORM.",
    ],
    devExp: [
      "      *=======================================",
      "      * PROGRAM: HELLO-WORLD",
      "      * AUTHOR:  MAINFRAME TEAM",
      "      * DATE:    1987-03-15",
      "      * PURPOSE: NOBODY REMEMBERS",
      "      *=======================================",
      "       IDENTIFICATION DIVISION.",
      "       PROGRAM-ID. HELLO-WORLD.",
      "       PROCEDURE DIVISION.",
      "       MAIN-PARA.",
      "           DISPLAY 'HELLO WORLD'.",
      "           DISPLAY 'STILL RUNNING IN PROD'.",
      "           DISPLAY 'SINCE 1987'.",
      "           DISPLAY 'PLEASE DO NOT TOUCH'.",
      "           STOP RUN.",
      "      * LAST MODIFIED: NEVER. IT WORKS.",
    ],
  },

  Dart: {
    speed: [
      "import 'dart:isolate';",
      "import 'dart:typed_data';",
      "",
      "Future<double> parallelSum(Float64List data) async {",
      "  final chunks = _split(data, Platform.numberOfProcessors);",
      "  final futures = chunks.map((chunk) =>",
      "    Isolate.run(() {",
      "      double sum = 0;",
      "      for (var i = 0; i < chunk.length; i++) {",
      "        sum += chunk[i] * chunk[i];",
      "      }",
      "      return sum;",
      "    }));",
      "",
      "  final results = await Future.wait(futures);",
      "  return results.fold(0.0, (a, b) => a + b);",
      "}",
    ],
    security: [
      "import 'package:pointycastle/export.dart';",
      "import 'dart:typed_data';",
      "import 'dart:convert';",
      "",
      "class CryptoService {",
      "  final _random = FortunaRandom();",
      "",
      "  Uint8List encrypt(String plaintext, Uint8List key) {",
      "    final iv = _random.nextBytes(16);",
      "    final cipher = GCMBlockCipher(AESEngine())",
      "      ..init(true, AEADParameters(",
      "        KeyParameter(key), 128, iv, Uint8List(0)));",
      "    final input = utf8.encode(plaintext);",
      "    final output = cipher.process(",
      "      Uint8List.fromList(input));",
      "    return Uint8List.fromList([...iv, ...output]);",
      "  }",
      "}",
    ],
    ecosystem: [
      "import 'package:flutter/material.dart';",
      "import 'package:flutter_bloc/flutter_bloc.dart';",
      "import 'package:dio/dio.dart';",
      "import 'package:hive/hive.dart';",
      "import 'package:get_it/get_it.dart';",
      "import 'package:freezed_annotation/freezed_annotation.dart';",
      "import 'package:json_serializable/json_serializable.dart';",
      "import 'package:go_router/go_router.dart';",
      "import 'package:riverpod/riverpod.dart';",
      "import 'package:drift/drift.dart';",
      "import 'package:firebase_core/firebase_core.dart';",
      "import 'package:shared_preferences/shared_preferences.dart';",
      "// pub.dev: Flutter's growing ecosystem",
      "// One codebase: iOS, Android, Web, Desktop",
    ],
    scalability: [
      "import 'dart:isolate';",
      "import 'dart:async';",
      "",
      "class WorkerPool<T, R> {",
      "  final List<Isolate> _isolates = [];",
      "  final List<SendPort> _ports = [];",
      "",
      "  Future<void> spawn(int count,",
      "      R Function(T) task) async {",
      "    for (var i = 0; i < count; i++) {",
      "      final rp = ReceivePort();",
      "      final isolate = await Isolate.spawn(",
      "        _workerEntry, [rp.sendPort, task]);",
      "      _isolates.add(isolate);",
      "      _ports.add(await rp.first as SendPort);",
      "    }",
      "  }",
      "",
      "  void dispose() {",
      "    for (final iso in _isolates) iso.kill();",
      "  }",
      "}",
    ],
    devExp: [
      "import 'package:flutter/material.dart';",
      "",
      "class CounterApp extends StatelessWidget {",
      "  const CounterApp({super.key});",
      "",
      "  @override",
      "  Widget build(BuildContext context) {",
      "    return MaterialApp(",
      "      theme: ThemeData.dark(useMaterial3: true),",
      "      home: Scaffold(",
      "        appBar: AppBar(title: const Text('Counter')),",
      "        body: Center(",
      "          child: ElevatedButton(",
      "            onPressed: () => setState(() => _c++),",
      "            child: Text('Count: $_c'),",
      "          )),",
      "      ));",
      "  }",
      "}",
    ],
  },

  Delphi: {
    speed: [
      "unit FastCompute;",
      "interface",
      "uses System.Threading, System.SysUtils;",
      "",
      "function ParallelSum(const Data: array of Double",
      "  ): Double;",
      "",
      "implementation",
      "",
      "function ParallelSum(const Data: array of Double",
      "  ): Double;",
      "var Total: Double;",
      "begin",
      "  Total := 0;",
      "  TParallel.For(0, High(Data),",
      "    procedure(I: Integer)",
      "    begin",
      "      AtomicAdd(Total, Data[I] * Data[I]);",
      "    end);",
      "  Result := Total;",
      "end;",
      "end.",
    ],
    security: [
      "unit SecureAuth;",
      "interface",
      "uses System.Hash, System.SysUtils,",
      "     System.NetEncoding;",
      "",
      "type",
      "  TAuthService = class",
      "  public",
      "    class function HashPassword(",
      "      const Password: string): string;",
      "    class function VerifyPassword(",
      "      const Password, Hash: string): Boolean;",
      "  end;",
      "",
      "implementation",
      "",
      "class function TAuthService.HashPassword(",
      "  const Password: string): string;",
      "begin",
      "  Result := THashBCrypt.HashPassword(Password);",
      "end;",
      "end.",
    ],
    ecosystem: [
      "unit MainForm;",
      "interface",
      "uses",
      "  System.SysUtils, System.Classes,",
      "  Vcl.Controls, Vcl.Forms, Vcl.Dialogs,",
      "  Vcl.StdCtrls, Vcl.ExtCtrls, Vcl.Grids,",
      "  Data.DB, Data.Win.ADODB,",
      "  FireDAC.Comp.Client, FireDAC.Stan.Def,",
      "  REST.Client, REST.Types, REST.Json,",
      "  System.JSON, System.Threading,",
      "  IdHTTP, IdSSLOpenSSL;",
      "",
      "// 30+ years of Windows development",
      "// RAD: drag-drop, compile, ship",
    ],
    scalability: [
      "unit WorkerPool;",
      "interface",
      "uses System.Classes, System.SyncObjs,",
      "     System.Generics.Collections;",
      "",
      "type",
      "  TWorkerPool = class",
      "  private",
      "    FThreads: TList<TThread>;",
      "    FQueue: TThreadedQueue<TProc>;",
      "  public",
      "    constructor Create(WorkerCount: Integer);",
      "    procedure Submit(const Task: TProc);",
      "    procedure WaitAll;",
      "    destructor Destroy; override;",
      "  end;",
      "",
      "implementation",
      "// Object Pascal concurrent task execution",
    ],
    devExp: [
      "unit MainForm;",
      "interface",
      "uses Vcl.Forms, Vcl.StdCtrls, Vcl.Controls;",
      "",
      "type",
      "  TForm1 = class(TForm)",
      "    BtnHello: TButton;",
      "    LblOutput: TLabel;",
      "    procedure BtnHelloClick(Sender: TObject);",
      "  end;",
      "",
      "implementation",
      "",
      "procedure TForm1.BtnHelloClick(Sender: TObject);",
      "begin",
      "  LblOutput.Caption := 'Hello from Delphi!';",
      "end;",
      "// Visual designer + compiled native code",
      "end.",
    ],
  },

  Elixir: {
    speed: [
      "defmodule Compute.Parallel do",
      "  @chunk_size 1_024",
      "",
      "  def parallel_map(collection, func) do",
      "    collection",
      "    |> Enum.chunk_every(@chunk_size)",
      "    |> Task.async_stream(",
      "         fn chunk -> Enum.map(chunk, func) end,",
      "         max_concurrency: System.schedulers_online()",
      "       )",
      "    |> Enum.flat_map(fn {:ok, result} ->",
      "         result end)",
      "  end",
      "",
      "  def transform(data) do",
      "    parallel_map(data, &(:math.sqrt(&1 * &1)))",
      "  end",
      "end",
    ],
    security: [
      "defmodule Auth.Token do",
      "  @moduledoc \"JWT token signing and verification\"",
      "",
      "  @secret Application.compile_env!(:app, :secret)",
      "",
      "  def sign(claims) when is_map(claims) do",
      "    payload = Jason.encode!(claims)",
      "    signature = :crypto.mac(",
      "      :hmac, :sha256, @secret, payload)",
      "    Base.url_encode64(signature)",
      "  end",
      "",
      "  def verify(payload, signature) do",
      "    expected = :crypto.mac(",
      "      :hmac, :sha256, @secret, payload)",
      "    Plug.Crypto.secure_compare(",
      "      signature, Base.url_encode64(expected))",
      "  end",
      "end",
    ],
    ecosystem: [
      "defmodule App.MixProject do",
      "  use Mix.Project",
      "",
      "  defp deps do",
      "    [",
      "      {:phoenix, \"~> 1.7\"},",
      "      {:phoenix_live_view, \"~> 0.20\"},",
      "      {:ecto_sql, \"~> 3.11\"},",
      "      {:postgrex, \">= 0.0.0\"},",
      "      {:oban, \"~> 2.17\"},",
      "      {:tesla, \"~> 1.8\"},",
      "      {:absinthe, \"~> 1.7\"},",
      "      {:broadway, \"~> 1.0\"},",
      "      {:nx, \"~> 0.7\"},",
      "      {:jason, \"~> 1.4\"},",
      "    ]",
      "  end",
      "end",
    ],
    scalability: [
      "defmodule Pipeline.Worker do",
      "  use GenServer",
      "",
      "  def start_link(opts) do",
      "    GenServer.start_link(__MODULE__, opts)",
      "  end",
      "",
      "  def init(state) do",
      "    {:ok, state}",
      "  end",
      "",
      "  def handle_cast({:process, data}, state) do",
      "    result = transform(data)",
      "    send(state.collector, {:result, result})",
      "    {:noreply, state}",
      "  end",
      "",
      "  def handle_info(:timeout, state) do",
      "    {:noreply, state, :hibernate}",
      "  end",
      "end",
    ],
    devExp: [
      "defmodule AppWeb.UserController do",
      "  use AppWeb, :controller",
      "",
      "  def index(conn, _params) do",
      "    users = Accounts.list_users()",
      "    render(conn, :index, users: users)",
      "  end",
      "",
      "  def create(conn, %{\"user\" => params}) do",
      "    case Accounts.create_user(params) do",
      "      {:ok, user} ->",
      "        conn",
      "        |> put_status(:created)",
      "        |> render(:show, user: user)",
      "      {:error, changeset} ->",
      "        conn",
      "        |> put_status(:unprocessable_entity)",
      "        |> render(:error, changeset: changeset)",
      "    end",
      "  end",
      "end",
    ],
  },

  Erlang: {
    speed: [
      "-module(fast_compute).",
      "-export([parallel_sum/1]).",
      "",
      "parallel_sum(Data) ->",
      "  NumCPU = erlang:system_info(schedulers),",
      "  Chunks = split(Data, NumCPU),",
      "  Parent = self(),",
      "  Pids = [spawn(fun() ->",
      "    Parent ! {self(), lists:foldl(",
      "      fun(X, Acc) -> Acc + X * X end,",
      "      0, Chunk)}",
      "  end) || Chunk <- Chunks],",
      "  collect(Pids, 0).",
      "",
      "collect([], Acc) -> Acc;",
      "collect([Pid | Rest], Acc) ->",
      "  receive {Pid, Sum} ->",
      "    collect(Rest, Acc + Sum)",
      "  end.",
    ],
    security: [
      "-module(auth).",
      "-export([hash_password/1, verify/2]).",
      "",
      "hash_password(Password) when is_binary(Password) ->",
      "  Salt = crypto:strong_rand_bytes(16),",
      "  Hash = crypto:hash(sha256,",
      "    <<Salt/binary, Password/binary>>),",
      "  {Salt, Hash}.",
      "",
      "verify(Password, {Salt, Expected}) ->",
      "  Hash = crypto:hash(sha256,",
      "    <<Salt/binary, Password/binary>>),",
      "  crypto:hash_equals(Hash, Expected).",
      "",
      "%% Pattern matching prevents injection",
      "%% Immutable data prevents tampering",
      "%% Let-it-crash isolates failures",
    ],
    ecosystem: [
      "-module(app).",
      "",
      "%% OTP applications",
      "-include_lib(\"kernel/include/logger.hrl\").",
      "-include_lib(\"stdlib/include/assert.hrl\").",
      "",
      "%% rebar3 deps",
      "%% {cowboy, \"2.12.0\"}     HTTP server",
      "%% {jsx, \"3.1.0\"}         JSON",
      "%% {hackney, \"1.20.1\"}    HTTP client",
      "%% {poolboy, \"1.5.2\"}     Worker pools",
      "%% {lager, \"3.9.2\"}       Logging",
      "%% {erlcass, \"4.0.0\"}     Cassandra",
      "%% {amqp_client, \"3.12\"} RabbitMQ",
      "",
      "%% Telecom-grade reliability since 1986",
    ],
    scalability: [
      "-module(supervisor_tree).",
      "-behaviour(supervisor).",
      "-export([init/1, start_link/0]).",
      "",
      "start_link() ->",
      "  supervisor:start_link({local, ?MODULE},",
      "    ?MODULE, []).",
      "",
      "init([]) ->",
      "  Children = [",
      "    #{id => worker_pool,",
      "      start => {worker_pool, start_link, []},",
      "      restart => permanent,",
      "      type => supervisor},",
      "    #{id => task_queue,",
      "      start => {task_queue, start_link, []},",
      "      restart => permanent}",
      "  ],",
      "  {ok, {{one_for_one, 5, 10}, Children}}.",
    ],
    devExp: [
      "-module(hello_server).",
      "-behaviour(gen_server).",
      "-export([start_link/0, greet/1]).",
      "-export([init/1, handle_call/3]).",
      "",
      "start_link() ->",
      "  gen_server:start_link(",
      "    {local, ?MODULE}, ?MODULE, [], []).",
      "",
      "init([]) -> {ok, #{count => 0}}.",
      "",
      "greet(Name) ->",
      "  gen_server:call(?MODULE, {greet, Name}).",
      "",
      "handle_call({greet, Name}, _From, State) ->",
      "  Count = maps:get(count, State) + 1,",
      "  Msg = io_lib:format(\"Hello ~s (#~B)\",",
      "    [Name, Count]),",
      "  {reply, Msg, State#{count => Count}}.",
    ],
  },

  Haskell: {
    speed: [
      "module Compute.Parallel where",
      "",
      "import Control.Parallel.Strategies",
      "import qualified Data.Vector.Unboxed as V",
      "",
      "parallelSum :: V.Vector Double -> Double",
      "parallelSum vec =",
      "  let chunks = V.chunksOf 1024 vec",
      "      sums = map (V.foldl' (\\acc x -> acc + x*x) 0)",
      "                 chunks",
      "             `using` parList rdeepseq",
      "  in sum sums",
      "",
      "-- | Strict left fold with fusion",
      "transform :: [Double] -> [Double]",
      "transform = map sqrt . filter (> 0)",
      "-- GHC optimizes to tight loop via rewrite rules",
    ],
    security: [
      "{-# LANGUAGE DataKinds #-}",
      "module Auth.Safe where",
      "",
      "import Crypto.Hash (SHA256, hash)",
      "import Data.ByteString (ByteString)",
      "",
      "newtype Password = Password ByteString",
      "newtype HashedPw = HashedPw ByteString",
      "",
      "hashPassword :: Password -> IO HashedPw",
      "hashPassword (Password pw) = do",
      "  salt <- getEntropy 16",
      "  let salted = salt <> pw",
      "  pure . HashedPw $ hash @SHA256 salted",
      "",
      "verify :: Password -> HashedPw -> Bool",
      "verify (Password pw) (HashedPw h) =",
      "  constantTimeEq (hash @SHA256 pw) h",
      "-- Newtypes: zero-cost type safety",
    ],
    ecosystem: [
      "module App.Main where",
      "",
      "import Servant",
      "import Database.Persist.Postgresql",
      "import Data.Aeson (FromJSON, ToJSON)",
      "import Control.Monad.Reader (ReaderT)",
      "import Conduit (ConduitT, runConduit)",
      "import Lens.Micro.Platform",
      "import qualified Data.Text as T",
      "import qualified Data.Map.Strict as Map",
      "import Network.Wai.Handler.Warp (run)",
      "import Katip (Severity(..), logMsg)",
      "import Test.QuickCheck (Arbitrary)",
      "import Options.Applicative",
      "-- stack.yaml: resolver: lts-22.0",
      "-- 16,000+ packages on Hackage",
    ],
    scalability: [
      "module Pipeline.STM where",
      "",
      "import Control.Concurrent.STM",
      "import Control.Concurrent.Async",
      "",
      "type WorkQueue a = TBQueue a",
      "",
      "fanOut :: Int -> WorkQueue a -> (a -> IO b)",
      "       -> IO [b]",
      "fanOut n queue work =",
      "  mapConcurrently id $ replicate n worker",
      "  where",
      "    worker = do",
      "      item <- atomically $ readTBQueue queue",
      "      work item",
      "",
      "-- STM: composable atomic transactions",
      "-- No deadlocks, no race conditions",
      "-- Retry semantics built in",
    ],
    devExp: [
      "module Api where",
      "",
      "import Servant",
      "import Data.Aeson (ToJSON, FromJSON)",
      "import GHC.Generics (Generic)",
      "",
      "data User = User",
      "  { userId   :: Int",
      "  , userName :: Text",
      "  , email    :: Text",
      "  } deriving (Show, Generic, ToJSON, FromJSON)",
      "",
      "type API = \"users\" :> Get '[JSON] [User]",
      "      :<|> \"users\" :> ReqBody '[JSON] User",
      "                   :> Post '[JSON] User",
      "",
      "-- Type-safe API: routes, params, responses",
      "-- If it compiles, the API is consistent",
    ],
  },

  Kotlin: {
    speed: [
      "import kotlinx.coroutines.*",
      "import kotlinx.coroutines.flow.*",
      "",
      "suspend fun parallelTransform(",
      "  data: List<Double>",
      "): List<Double> = coroutineScope {",
      "  data.chunked(1024)",
      "    .map { chunk ->",
      "      async(Dispatchers.Default) {",
      "        chunk.map { x ->",
      "          kotlin.math.sqrt(x * x + 1.0)",
      "        }",
      "      }",
      "    }",
      "    .awaitAll()",
      "    .flatten()",
      "}",
    ],
    security: [
      "import javax.crypto.Mac",
      "import javax.crypto.spec.SecretKeySpec",
      "import java.security.MessageDigest",
      "",
      "class TokenService(private val secret: ByteArray) {",
      "",
      "  fun sign(payload: String): String {",
      "    val mac = Mac.getInstance(\"HmacSHA256\")",
      "    mac.init(SecretKeySpec(secret, \"HmacSHA256\"))",
      "    return mac.doFinal(payload.toByteArray())",
      "      .joinToString(\"\") { \"%02x\".format(it) }",
      "  }",
      "",
      "  fun verify(payload: String, sig: String): Boolean {",
      "    val expected = sign(payload)",
      "    return MessageDigest.isEqual(",
      "      expected.toByteArray(), sig.toByteArray())",
      "  }",
      "}",
    ],
    ecosystem: [
      "import io.ktor.server.application.*",
      "import io.ktor.server.routing.*",
      "import org.jetbrains.exposed.sql.*",
      "import kotlinx.serialization.*",
      "import kotlinx.coroutines.flow.*",
      "import arrow.core.Either",
      "import io.kotest.core.spec.style.StringSpec",
      "import org.koin.core.module.dsl.singleOf",
      "import okhttp3.OkHttpClient",
      "import com.squareup.moshi.Moshi",
      "import io.github.oshai.kotlinlogging.KotlinLogging",
      "import org.jetbrains.compose.web.dom.*",
      "// Kotlin: JVM, JS, Native, Multiplatform",
      "// From Android to server to WASM",
    ],
    scalability: [
      "import kotlinx.coroutines.*",
      "import kotlinx.coroutines.channels.*",
      "",
      "fun CoroutineScope.fanOut(",
      "  input: ReceiveChannel<Task>,",
      "  workers: Int",
      "): ReceiveChannel<Result> {",
      "  val output = Channel<Result>(256)",
      "  repeat(workers) {",
      "    launch {",
      "      for (task in input) {",
      "        val result = process(task)",
      "        output.send(result)",
      "      }",
      "    }",
      "  }",
      "  return output",
      "}",
    ],
    devExp: [
      "import io.ktor.server.application.*",
      "import io.ktor.server.response.*",
      "import io.ktor.server.routing.*",
      "import kotlinx.serialization.Serializable",
      "",
      "@Serializable",
      "data class User(",
      "  val id: Int,",
      "  val name: String,",
      "  val email: String",
      ")",
      "",
      "fun Application.configureRouting() {",
      "  routing {",
      "    get(\"/users\") {",
      "      call.respond(userService.findAll())",
      "    }",
      "    post(\"/users\") {",
      "      val user = call.receive<User>()",
      "      call.respond(userService.create(user))",
      "    }",
      "  }",
      "}",
    ],
  },

  Lua: {
    speed: [
      "local ffi = require('ffi')",
      "local bit = require('bit')",
      "",
      "ffi.cdef[[",
      "  typedef struct { double x, y, z; } vec3_t;",
      "]]",
      "",
      "local function dot_product(a, b, n)",
      "  local sum = 0.0",
      "  for i = 0, n - 1 do",
      "    sum = sum + a[i].x * b[i].x",
      "              + a[i].y * b[i].y",
      "              + a[i].z * b[i].z",
      "  end",
      "  return sum",
      "end",
      "-- LuaJIT: traces this to machine code",
    ],
    security: [
      "local openssl = require('openssl')",
      "local digest = require('openssl.digest')",
      "local hmac = require('openssl.hmac')",
      "",
      "local M = {}",
      "",
      "function M.hash_password(password, salt)",
      "  salt = salt or openssl.random(16)",
      "  local h = digest.new('sha256')",
      "  h:update(salt)",
      "  h:update(password)",
      "  return salt .. h:final(), salt",
      "end",
      "",
      "function M.verify(password, salt, expected)",
      "  local hash = M.hash_password(password, salt)",
      "  return openssl.memcmp(hash, expected) == 0",
      "end",
      "",
      "return M",
    ],
    ecosystem: [
      "-- LuaRocks dependencies",
      "local lapis = require('lapis')",
      "local cjson = require('cjson')",
      "local redis = require('resty.redis')",
      "local mysql = require('resty.mysql')",
      "local http = require('resty.http')",
      "local template = require('resty.template')",
      "local uuid = require('resty.jit-uuid')",
      "local upload = require('resty.upload')",
      "",
      "-- OpenResty / NGINX + Lua = fast web",
      "-- Neovim plugins, game scripting (WoW, Roblox)",
      "-- Redis EVAL, NGINX access_by_lua",
      "-- Embedded everywhere, tiny footprint",
    ],
    scalability: [
      "local copas = require('copas')",
      "local socket = require('socket')",
      "",
      "local function worker(task_queue, results)",
      "  while true do",
      "    local task = task_queue:receive()",
      "    if not task then break end",
      "    local ok, result = pcall(process, task)",
      "    if ok then",
      "      results:send(result)",
      "    end",
      "  end",
      "end",
      "",
      "-- Spawn coroutine workers",
      "for i = 1, 8 do",
      "  copas.addthread(worker, tasks, results)",
      "end",
      "copas.loop()",
    ],
    devExp: [
      "-- Simple config & scripting",
      "local config = {",
      "  host = '0.0.0.0',",
      "  port = 8080,",
      "  database = {",
      "    driver = 'postgres',",
      "    name = 'myapp',",
      "  },",
      "  logging = true,",
      "}",
      "",
      "function config:validate()",
      "  assert(self.host, 'host required')",
      "  assert(self.port > 0, 'invalid port')",
      "  return true",
      "end",
      "",
      "return config",
      "-- Lua: the ultimate embedded language",
    ],
  },

  MATLAB: {
    speed: [
      "function result = parallel_compute(data)",
      "  % Vectorized matrix operation",
      "  A = reshape(data, [], 1024);",
      "  B = A' * A;  % matrix multiply (BLAS)",
      "",
      "  % GPU acceleration",
      "  gA = gpuArray(A);",
      "  gB = gA' * gA;",
      "  result = gather(gB);",
      "",
      "  % Parallel pool",
      "  parfor i = 1:size(A, 1)",
      "    result(i,:) = fft(A(i,:));",
      "  end",
      "end",
      "% MATLAB: matrix ops are native operations",
    ],
    security: [
      "function [encrypted, key] = secure_data(data)",
      "  % Generate AES key",
      "  key = java.security.SecureRandom();",
      "  keyBytes = zeros(1, 32, 'uint8');",
      "  key.nextBytes(keyBytes);",
      "",
      "  % SHA-256 hash for integrity",
      "  md = java.security.MessageDigest.getInstance(",
      "    'SHA-256');",
      "  hash = typecast(md.digest(",
      "    uint8(data)), 'uint8');",
      "",
      "  % Encrypt via Java interop",
      "  cipher = javax.crypto.Cipher.getInstance(",
      "    'AES/GCM/NoPadding');",
      "  encrypted = cipher.doFinal(uint8(data));",
      "end",
    ],
    ecosystem: [
      "% MATLAB Toolbox imports",
      "% Signal Processing Toolbox",
      "% Image Processing Toolbox",
      "% Statistics and Machine Learning Toolbox",
      "% Deep Learning Toolbox",
      "% Control System Toolbox",
      "% Robotics System Toolbox",
      "% Simulink",
      "% Parallel Computing Toolbox",
      "% Optimization Toolbox",
      "% Computer Vision Toolbox",
      "% Communications Toolbox",
      "% Aerospace Toolbox",
      "% Bioinformatics Toolbox",
      "% Econometrics Toolbox",
      "% 80+ toolboxes for science & engineering",
    ],
    scalability: [
      "function results = distributed_job(data)",
      "  % Create parallel pool",
      "  pool = parpool('Processes', 16);",
      "",
      "  % Distributed array",
      "  D = distributed(data);",
      "",
      "  % SPMD block: runs on all workers",
      "  spmd",
      "    localData = getLocalPart(D);",
      "    localResult = process(localData);",
      "    labSend(localResult, 1);",
      "  end",
      "",
      "  % Collect results",
      "  results = gather(D);",
      "  delete(pool);",
      "end",
    ],
    devExp: [
      "% Quick data analysis script",
      "data = readtable('experiment.csv');",
      "disp(head(data));",
      "",
      "% Filter and transform",
      "valid = data(data.value > 0, :);",
      "valid.normalized = normalize(valid.value);",
      "",
      "% Visualize",
      "figure;",
      "subplot(1,2,1);",
      "histogram(valid.normalized);",
      "title('Distribution');",
      "subplot(1,2,2);",
      "scatter(valid.x, valid.y, 'filled');",
      "title('X vs Y');",
      "% From data to plot in 15 lines",
    ],
  },

  Pascal: {
    speed: [
      "program FastSort;",
      "uses SysUtils;",
      "",
      "procedure QuickSort(var A: array of Integer;",
      "  Lo, Hi: Integer);",
      "var",
      "  Pivot, Temp, I, J: Integer;",
      "begin",
      "  I := Lo; J := Hi;",
      "  Pivot := A[(Lo + Hi) div 2];",
      "  repeat",
      "    while A[I] < Pivot do Inc(I);",
      "    while A[J] > Pivot do Dec(J);",
      "    if I <= J then begin",
      "      Temp := A[I]; A[I] := A[J];",
      "      A[J] := Temp;",
      "      Inc(I); Dec(J);",
      "    end;",
      "  until I > J;",
      "  if Lo < J then QuickSort(A, Lo, J);",
      "  if I < Hi then QuickSort(A, I, Hi);",
      "end;",
    ],
    security: [
      "program SecureInput;",
      "uses SysUtils, Classes;",
      "",
      "function SanitizeInput(",
      "  const Input: string): string;",
      "var",
      "  I: Integer;",
      "  Ch: Char;",
      "begin",
      "  Result := '';",
      "  for I := 1 to Length(Input) do begin",
      "    Ch := Input[I];",
      "    if Ch in ['a'..'z', 'A'..'Z', '0'..'9',",
      "              ' ', '.', '-'] then",
      "      Result := Result + Ch;",
      "  end;",
      "  if Length(Result) > 255 then",
      "    Result := Copy(Result, 1, 255);",
      "end;",
    ],
    ecosystem: [
      "program MainApp;",
      "uses",
      "  SysUtils, Classes, StrUtils,",
      "  Math, DateUtils,",
      "  DB, SQLdb, PQConnection,",
      "  fphttpclient, fpjson, jsonparser,",
      "  RegExpr, Zipper,",
      "  fgl, Generics.Collections;",
      "",
      "{ Free Pascal / Lazarus ecosystem }",
      "{ Cross-platform GUI via LCL }",
      "{ FCL: Free Component Library }",
      "{ Database, networking, XML, JSON }",
      "{ 40+ years of structured programming }",
    ],
    scalability: [
      "program ThreadWorkers;",
      "uses Classes, SysUtils, SyncObjs;",
      "",
      "type",
      "  TWorker = class(TThread)",
      "  private",
      "    FTask: string;",
      "    FLock: TCriticalSection;",
      "  protected",
      "    procedure Execute; override;",
      "  end;",
      "",
      "procedure TWorker.Execute;",
      "begin",
      "  FLock.Enter;",
      "  try",
      "    ProcessTask(FTask);",
      "  finally",
      "    FLock.Leave;",
      "  end;",
      "end;",
    ],
    devExp: [
      "program HelloPascal;",
      "uses SysUtils;",
      "",
      "type",
      "  TStudent = record",
      "    Name: string;",
      "    Grade: Integer;",
      "  end;",
      "",
      "var",
      "  Students: array[1..3] of TStudent;",
      "  I: Integer;",
      "begin",
      "  Students[1].Name := 'Alice';",
      "  Students[1].Grade := 95;",
      "  for I := 1 to 3 do",
      "    WriteLn(Students[I].Name, ': ',",
      "      Students[I].Grade);",
      "  { Clear, structured, readable }",
      "end.",
    ],
  },

  Perl: {
    speed: [
      "use strict;",
      "use warnings;",
      "use Parallel::ForkManager;",
      "",
      "my $pm = Parallel::ForkManager->new(8);",
      "my @results;",
      "",
      "$pm->run_on_finish(sub {",
      "  my ($pid, $code, $id, $sig, $dump, $data) = @_;",
      "  push @results, $$data if $data;",
      "});",
      "",
      "for my $chunk (@data_chunks) {",
      "  $pm->start and next;",
      "  my $sum = 0;",
      "  $sum += $_ ** 2 for @$chunk;",
      "  $pm->finish(0, \\$sum);",
      "}",
      "$pm->wait_all_children;",
    ],
    security: [
      "use strict;",
      "use warnings;",
      "use Crypt::Bcrypt qw(bcrypt bcrypt_check);",
      "use Crypt::URandom qw(urandom);",
      "",
      "sub hash_password {",
      "  my ($password) = @_;",
      "  my $salt = urandom(16);",
      "  return bcrypt($password, '2b', 12, $salt);",
      "}",
      "",
      "sub verify_password {",
      "  my ($password, $hash) = @_;",
      "  return bcrypt_check($password, $hash);",
      "}",
      "",
      "# Taint mode: perl -T script.pl",
      "# Untrusted data must be sanitized",
      "# $input =~ /^([\\w.-]+)$/ or die;",
    ],
    ecosystem: [
      "use Mojolicious::Lite -signatures;",
      "use DBI;",
      "use JSON::XS;",
      "use LWP::UserAgent;",
      "use Text::CSV;",
      "use DateTime;",
      "use Try::Tiny;",
      "use Path::Tiny;",
      "use Moose;",
      "use Template;",
      "use Log::Log4perl;",
      "use File::Find::Rule;",
      "use XML::LibXML;",
      "use IO::Async::Loop;",
      "# CPAN: 200,000+ modules",
      "# \"There's more than one way to do it\"",
    ],
    scalability: [
      "use strict;",
      "use warnings;",
      "use AnyEvent;",
      "use AnyEvent::HTTP;",
      "",
      "my $cv = AnyEvent->condvar;",
      "my @results;",
      "",
      "for my $url (@urls) {",
      "  $cv->begin;",
      "  http_get $url, sub {",
      "    my ($body, $hdr) = @_;",
      "    push @results, {",
      "      url    => $url,",
      "      status => $hdr->{Status},",
      "      size   => length($body // ''),",
      "    };",
      "    $cv->end;",
      "  };",
      "}",
      "$cv->recv;  # wait for all requests",
    ],
    devExp: [
      "#!/usr/bin/env perl",
      "use Mojolicious::Lite -signatures;",
      "",
      "# One-liner web app",
      "get '/' => {text => 'Hello, Perl!'};",
      "",
      "get '/greet/:name' => sub ($c) {",
      "  my $name = $c->param('name');",
      "  $c->render(text => \"Hello, $name!\");",
      "};",
      "",
      "post '/echo' => sub ($c) {",
      "  my $body = $c->req->json;",
      "  $c->render(json => $body);",
      "};",
      "",
      "app->start;",
      "# morbo app.pl  => reload on save",
    ],
  },

  PHP: {
    speed: [
      "<?php declare(strict_types=1);",
      "",
      "function parallelProcess(array $data): array {",
      "  $runtime = new \\parallel\\Runtime();",
      "  $futures = [];",
      "",
      "  foreach (array_chunk($data, 1000) as $chunk) {",
      "    $futures[] = $runtime->run(",
      "      function(array $c): float {",
      "        $sum = 0.0;",
      "        foreach ($c as $v) {",
      "          $sum += $v * $v;",
      "        }",
      "        return $sum;",
      "      }, [$chunk]",
      "    );",
      "  }",
      "",
      "  return array_map(fn($f) => $f->value(),",
      "    $futures);",
      "}",
    ],
    security: [
      "<?php declare(strict_types=1);",
      "",
      "namespace App\\Security;",
      "",
      "class AuthService {",
      "  public function hashPassword(string $pw): string {",
      "    return password_hash($pw, PASSWORD_ARGON2ID, [",
      "      'memory_cost' => 65536,",
      "      'time_cost'   => 4,",
      "      'threads'     => 3,",
      "    ]);",
      "  }",
      "",
      "  public function verify(string $pw,",
      "                         string $hash): bool {",
      "    return password_verify($pw, $hash);",
      "  }",
      "",
      "  public function needsRehash(string $hash): bool {",
      "    return password_needs_rehash(",
      "      $hash, PASSWORD_ARGON2ID);",
      "  }",
      "}",
    ],
    ecosystem: [
      "<?php",
      "// composer.json dependencies",
      "use Illuminate\\Support\\Facades\\Route;",
      "use Illuminate\\Http\\Request;",
      "use Doctrine\\ORM\\EntityManager;",
      "use Symfony\\Component\\Console\\Command;",
      "use GuzzleHttp\\Client;",
      "use Carbon\\Carbon;",
      "use PHPUnit\\Framework\\TestCase;",
      "use Monolog\\Logger;",
      "use League\\Flysystem\\Filesystem;",
      "use Intervention\\Image\\ImageManager;",
      "use Predis\\Client as Redis;",
      "use PhpAmqpLib\\Connection\\AMQPConnection;",
      "// Packagist: 400,000+ packages",
      "// Powers 77% of the web (WordPress alone)",
    ],
    scalability: [
      "<?php declare(strict_types=1);",
      "",
      "namespace App\\Queue;",
      "",
      "use Illuminate\\Bus\\Queueable;",
      "use Illuminate\\Contracts\\Queue\\ShouldQueue;",
      "use Illuminate\\Queue\\InteractsWithQueue;",
      "",
      "class ProcessOrder implements ShouldQueue {",
      "  use Queueable, InteractsWithQueue;",
      "",
      "  public int $tries = 3;",
      "  public int $backoff = 60;",
      "",
      "  public function __construct(",
      "    private readonly Order $order",
      "  ) {}",
      "",
      "  public function handle(): void {",
      "    $this->order->process();",
      "    event(new OrderProcessed($this->order));",
      "  }",
      "}",
    ],
    devExp: [
      "<?php",
      "// routes/api.php - Laravel",
      "use App\\Models\\User;",
      "use Illuminate\\Http\\Request;",
      "",
      "Route::get('/users', function () {",
      "  return User::paginate(15);",
      "});",
      "",
      "Route::post('/users', function (Request $req) {",
      "  $validated = $req->validate([",
      "    'name'  => 'required|string|max:255',",
      "    'email' => 'required|email|unique:users',",
      "  ]);",
      "  return User::create($validated);",
      "});",
      "",
      "// php artisan serve => done",
      "// Built-in ORM, validation, auth, queues",
    ],
  },

  R: {
    speed: [
      "library(parallel)",
      "library(Rcpp)",
      "",
      "# Vectorized R (calls C under the hood)",
      "fast_transform <- function(x) {",
      "  sqrt(x^2 + 1)  # vectorized, no loop needed",
      "}",
      "",
      "# Parallel computation",
      "parallel_apply <- function(data, func) {",
      "  cores <- detectCores() - 1",
      "  cl <- makeCluster(cores)",
      "  chunks <- split(data,",
      "    cut(seq_along(data), cores))",
      "  results <- parLapply(cl, chunks, func)",
      "  stopCluster(cl)",
      "  unlist(results)",
      "}",
    ],
    security: [
      "library(openssl)",
      "library(sodium)",
      "library(digest)",
      "",
      "hash_password <- function(password) {",
      "  salt <- random(16)",
      "  key <- argon2(charToRaw(password), salt)",
      "  list(hash = key, salt = salt)",
      "}",
      "",
      "verify_password <- function(password, stored) {",
      "  key <- argon2(charToRaw(password), stored$salt)",
      "  identical(key, stored$hash)",
      "}",
      "",
      "sign_data <- function(data, key) {",
      "  sha256(serialize(data, NULL), key = key)",
      "}",
    ],
    ecosystem: [
      "library(tidyverse)    # dplyr, ggplot2, tidyr",
      "library(data.table)   # fast data manipulation",
      "library(shiny)        # web applications",
      "library(caret)        # machine learning",
      "library(xgboost)      # gradient boosting",
      "library(plotly)       # interactive plots",
      "library(DBI)          # database interface",
      "library(httr2)        # HTTP client",
      "library(rmarkdown)    # reports & documents",
      "library(testthat)     # unit testing",
      "library(devtools)     # package development",
      "library(bioconductor) # genomics",
      "library(sf)           # geospatial",
      "# CRAN: 20,000+ packages",
      "# The language of statistics",
    ],
    scalability: [
      "library(future)",
      "library(furrr)",
      "",
      "# Switch backend: sequential, multicore, cluster",
      "plan(multisession, workers = 8)",
      "",
      "# Parallel map with futures",
      "results <- future_map(data_chunks, function(chunk) {",
      "  chunk %>%",
      "    mutate(score = compute_score(value)) %>%",
      "    filter(score > threshold) %>%",
      "    summarise(total = sum(score))",
      "}, .options = furrr_options(seed = TRUE))",
      "",
      "# Combine results",
      "final <- bind_rows(results)",
      "plan(sequential)  # clean up",
    ],
    devExp: [
      "library(tidyverse)",
      "",
      "# Data analysis in 15 lines",
      "df <- read_csv('experiment.csv')",
      "",
      "summary <- df %>%",
      "  filter(!is.na(value)) %>%",
      "  group_by(category) %>%",
      "  summarise(",
      "    mean = mean(value),",
      "    sd = sd(value),",
      "    n = n()",
      "  )",
      "",
      "ggplot(summary, aes(x = category, y = mean)) +",
      "  geom_col(fill = 'steelblue') +",
      "  geom_errorbar(aes(ymin = mean - sd,",
      "    ymax = mean + sd)) +",
      "  theme_minimal()",
    ],
  },

  Ruby: {
    speed: [
      "require 'parallel'",
      "require 'benchmark/ips'",
      "",
      "def parallel_transform(data)",
      "  Parallel.map(data.each_slice(1024),",
      "    in_processes: Etc.nprocessors) do |chunk|",
      "    chunk.map { |x| Math.sqrt(x ** 2 + 1) }",
      "  end.flatten",
      "end",
      "",
      "Benchmark.ips do |x|",
      "  data = Array.new(100_000) { rand }",
      "  x.report('sequential') { data.map { |v| v**2 } }",
      "  x.report('parallel') { parallel_transform(data) }",
      "  x.compare!",
      "end",
    ],
    security: [
      "require 'bcrypt'",
      "require 'openssl'",
      "require 'securerandom'",
      "",
      "class AuthService",
      "  def hash_password(password)",
      "    BCrypt::Password.create(password, cost: 12)",
      "  end",
      "",
      "  def verify(password, hash)",
      "    BCrypt::Password.new(hash) == password",
      "  end",
      "",
      "  def generate_token(payload)",
      "    key = OpenSSL::HMAC.digest(",
      "      'SHA256', ENV['SECRET_KEY'], payload)",
      "    Base64.urlsafe_encode64(key)",
      "  end",
      "end",
    ],
    ecosystem: [
      "# Gemfile",
      "source 'https://rubygems.org'",
      "",
      "gem 'rails', '~> 7.1'",
      "gem 'puma', '~> 6.0'",
      "gem 'pg'",
      "gem 'redis'",
      "gem 'sidekiq'",
      "gem 'devise'",
      "gem 'pundit'",
      "gem 'rspec-rails'",
      "gem 'rubocop'",
      "gem 'dry-validation'",
      "gem 'faraday'",
      "gem 'stripe'",
      "# bundle install => done",
      "# Rails: convention over configuration",
    ],
    scalability: [
      "require 'async'",
      "require 'async/http/internet'",
      "",
      "Async do",
      "  internet = Async::HTTP::Internet.new",
      "  barrier = Async::Barrier.new",
      "  semaphore = Async::Semaphore.new(50,",
      "    parent: barrier)",
      "  results = []",
      "",
      "  urls.each do |url|",
      "    semaphore.async do",
      "      response = internet.get(url)",
      "      results << {",
      "        url: url,",
      "        status: response.status,",
      "        body: response.read",
      "      }",
      "    end",
      "  end",
      "",
      "  barrier.wait",
      "end",
    ],
    devExp: [
      "# app/controllers/users_controller.rb",
      "class UsersController < ApplicationController",
      "  before_action :authenticate_user!",
      "",
      "  def index",
      "    @users = User.where(active: true)",
      "                 .order(created_at: :desc)",
      "                 .page(params[:page])",
      "    render json: @users",
      "  end",
      "",
      "  def create",
      "    @user = User.new(user_params)",
      "    if @user.save",
      "      render json: @user, status: :created",
      "    else",
      "      render json: @user.errors, status: 422",
      "    end",
      "  end",
      "end",
    ],
  },

  Scala: {
    speed: [
      "import scala.collection.parallel.CollectionConverters._",
      "import scala.collection.parallel.immutable.ParVector",
      "",
      "object FastCompute {",
      "  def parallelTransform(data: Vector[Double])",
      "    : Vector[Double] = {",
      "    data.par",
      "      .map(x => math.sqrt(x * x + 1.0))",
      "      .seq",
      "      .toVector",
      "  }",
      "",
      "  def foldSum(data: ParVector[Double]): Double =",
      "    data.aggregate(0.0)(",
      "      _ + _, _ + _",
      "    )",
      "}",
    ],
    security: [
      "import javax.crypto.Mac",
      "import javax.crypto.spec.SecretKeySpec",
      "import java.security.MessageDigest",
      "",
      "sealed trait AuthResult",
      "case class Authenticated(userId: String)",
      "  extends AuthResult",
      "case class Denied(reason: String)",
      "  extends AuthResult",
      "",
      "class TokenService(secret: Array[Byte]) {",
      "  def sign(payload: String): String = {",
      "    val mac = Mac.getInstance(\"HmacSHA256\")",
      "    mac.init(new SecretKeySpec(secret, \"HmacSHA256\"))",
      "    mac.doFinal(payload.getBytes(\"UTF-8\"))",
      "      .map(\"%02x\".format(_)).mkString",
      "  }",
      "}",
    ],
    ecosystem: [
      "import akka.actor.typed.ActorSystem",
      "import akka.http.scaladsl.Http",
      "import slick.jdbc.PostgresProfile.api._",
      "import cats.effect.IO",
      "import fs2.Stream",
      "import io.circe.generic.auto._",
      "import org.apache.spark.sql.SparkSession",
      "import zio.{ZIO, Task, Runtime}",
      "import sttp.client3._",
      "import com.typesafe.config.ConfigFactory",
      "import org.scalatest.flatspec.AnyFlatSpec",
      "import play.api.mvc._",
      "// Scala: FP + OOP on the JVM",
      "// Spark, Akka, Cats, ZIO ecosystem",
    ],
    scalability: [
      "import akka.actor.typed._",
      "import akka.actor.typed.scaladsl._",
      "",
      "object Worker {",
      "  sealed trait Command",
      "  case class Process(data: String,",
      "    replyTo: ActorRef[Result]) extends Command",
      "  case class Result(value: String)",
      "",
      "  def apply(): Behavior[Command] =",
      "    Behaviors.receive { (ctx, msg) =>",
      "      msg match {",
      "        case Process(data, replyTo) =>",
      "          val result = transform(data)",
      "          replyTo ! Result(result)",
      "          Behaviors.same",
      "      }",
      "    }",
      "}",
    ],
    devExp: [
      "import io.circe.generic.auto._",
      "import sttp.tapir._",
      "import sttp.tapir.json.circe._",
      "import sttp.tapir.server.netty._",
      "",
      "case class User(id: Int, name: String,",
      "  email: String)",
      "",
      "val getUsers = endpoint.get",
      "  .in(\"users\")",
      "  .out(jsonBody[List[User]])",
      "",
      "val createUser = endpoint.post",
      "  .in(\"users\")",
      "  .in(jsonBody[User])",
      "  .out(jsonBody[User])",
      "",
      "// Type-safe endpoints, auto-generated docs",
      "// If it compiles, the API contract is valid",
    ],
  },

  SQL: {
    speed: [
      "-- Optimized query with covering index",
      "CREATE INDEX CONCURRENTLY idx_orders_fast",
      "  ON orders (customer_id, created_at DESC)",
      "  INCLUDE (total, status);",
      "",
      "EXPLAIN ANALYZE",
      "SELECT customer_id,",
      "       SUM(total) AS revenue,",
      "       COUNT(*) AS order_count",
      "FROM orders",
      "WHERE created_at >= NOW() - INTERVAL '30 days'",
      "  AND status = 'completed'",
      "GROUP BY customer_id",
      "HAVING SUM(total) > 1000",
      "ORDER BY revenue DESC",
      "LIMIT 100;",
      "-- Index-only scan, no table access",
    ],
    security: [
      "-- Row-level security",
      "ALTER TABLE documents ENABLE ROW LEVEL SECURITY;",
      "",
      "CREATE POLICY tenant_isolation ON documents",
      "  USING (tenant_id = current_setting(",
      "    'app.current_tenant')::uuid);",
      "",
      "-- Parameterized queries prevent injection",
      "PREPARE get_user(text) AS",
      "  SELECT id, name, email",
      "  FROM users",
      "  WHERE email = $1;",
      "",
      "EXECUTE get_user('user@example.com');",
      "",
      "-- Grant minimal privileges",
      "GRANT SELECT ON users TO app_readonly;",
      "REVOKE ALL ON admin_logs FROM PUBLIC;",
    ],
    ecosystem: [
      "-- PostgreSQL extensions",
      "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
      "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
      "CREATE EXTENSION IF NOT EXISTS postgis;",
      "CREATE EXTENSION IF NOT EXISTS hstore;",
      "CREATE EXTENSION IF NOT EXISTS uuid-ossp;",
      "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;",
      "CREATE EXTENSION IF NOT EXISTS timescaledb;",
      "CREATE EXTENSION IF NOT EXISTS citus;",
      "",
      "-- Functions, triggers, CTEs, window functions",
      "-- JSON/JSONB, full-text search, GIS",
      "-- Materialized views, partitioning",
      "-- The most advanced open source database",
    ],
    scalability: [
      "-- Declarative partitioning",
      "CREATE TABLE events (",
      "  id         BIGINT GENERATED ALWAYS AS IDENTITY,",
      "  created_at TIMESTAMPTZ NOT NULL,",
      "  payload    JSONB NOT NULL",
      ") PARTITION BY RANGE (created_at);",
      "",
      "CREATE TABLE events_2026_01 PARTITION OF events",
      "  FOR VALUES FROM ('2026-01-01')",
      "  TO ('2026-02-01');",
      "",
      "-- Parallel query execution",
      "SET max_parallel_workers_per_gather = 4;",
      "",
      "-- Read replicas for scale-out reads",
      "-- Connection pooling via PgBouncer",
      "-- Sharding via Citus for 100B+ rows",
    ],
    devExp: [
      "-- Schema + seed in one file",
      "CREATE TABLE users (",
      "  id    SERIAL PRIMARY KEY,",
      "  name  TEXT NOT NULL,",
      "  email TEXT UNIQUE NOT NULL,",
      "  created_at TIMESTAMPTZ DEFAULT NOW()",
      ");",
      "",
      "INSERT INTO users (name, email) VALUES",
      "  ('Alice', 'alice@example.com'),",
      "  ('Bob', 'bob@example.com');",
      "",
      "-- Quick analytics",
      "SELECT name, email,",
      "  AGE(NOW(), created_at) AS member_for",
      "FROM users",
      "ORDER BY created_at DESC;",
    ],
  },

  Swift: {
    speed: [
      "import Accelerate",
      "",
      "func simdDotProduct(_ a: [Float],",
      "                    _ b: [Float]) -> Float {",
      "  precondition(a.count == b.count)",
      "  var result: Float = 0",
      "  vDSP_dotpr(a, 1, b, 1, &result,",
      "    vDSP_Length(a.count))",
      "  return result",
      "}",
      "",
      "func parallelTransform(",
      "  _ data: [Double]) async -> [Double] {",
      "  await withTaskGroup(of: [Double].self) { group in",
      "    for chunk in data.chunks(ofCount: 1024) {",
      "      group.addTask { chunk.map { sqrt($0 * $0) } }",
      "    }",
      "    return await group.reduce([], +)",
      "  }",
      "}",
    ],
    security: [
      "import CryptoKit",
      "import Foundation",
      "",
      "struct TokenService {",
      "  private let key: SymmetricKey",
      "",
      "  init(keyData: Data) {",
      "    self.key = SymmetricKey(data: keyData)",
      "  }",
      "",
      "  func sign(_ payload: Data) -> Data {",
      "    let auth = HMAC<SHA256>.authenticationCode(",
      "      for: payload, using: key)",
      "    return Data(auth)",
      "  }",
      "",
      "  func verify(_ payload: Data,",
      "              signature: Data) -> Bool {",
      "    HMAC<SHA256>.isValidAuthenticationCode(",
      "      signature, authenticating: payload,",
      "      using: key)",
      "  }",
      "}",
    ],
    ecosystem: [
      "import SwiftUI",
      "import Combine",
      "import Foundation",
      "import SwiftData",
      "import Observation",
      "// SPM dependencies",
      "import Alamofire",
      "import Vapor",
      "import GRDB",
      "import Kingfisher",
      "import SnapKit",
      "import SwiftProtobuf",
      "import ArgumentParser",
      "// Apple frameworks: UIKit, CoreData, ARKit",
      "// Server-side Swift: Vapor, Hummingbird",
      "// iOS, macOS, watchOS, tvOS, visionOS, Linux",
    ],
    scalability: [
      "import Foundation",
      "",
      "actor WorkerPool<T: Sendable> {",
      "  private var tasks: [() async -> T] = []",
      "  private let maxConcurrency: Int",
      "",
      "  init(maxConcurrency: Int = 8) {",
      "    self.maxConcurrency = maxConcurrency",
      "  }",
      "",
      "  func submit(_ work: @escaping () async -> T) {",
      "    tasks.append(work)",
      "  }",
      "",
      "  func executeAll() async -> [T] {",
      "    await withTaskGroup(of: T.self) { group in",
      "      for task in tasks {",
      "        group.addTask { await task() }",
      "      }",
      "      return await group.reduce(into: []) {",
      "        $0.append($1) }",
      "    }",
      "  }",
      "}",
    ],
    devExp: [
      "import SwiftUI",
      "",
      "struct ContentView: View {",
      "  @State private var count = 0",
      "",
      "  var body: some View {",
      "    VStack(spacing: 20) {",
      "      Text(\"Count: \\(count)\")",
      "        .font(.largeTitle)",
      "",
      "      Button(\"Increment\") {",
      "        withAnimation { count += 1 }",
      "      }",
      "      .buttonStyle(.borderedProminent)",
      "    }",
      "    .padding()",
      "  }",
      "}",
      "",
      "#Preview { ContentView() }",
    ],
  },
};

/** Merge all dimensions into one long code wall for a language */
export function getAllCode(language: string): string[] {
  const code = BATTLE_CODE[language] ?? BATTLE_CODE.C;
  return [
    ...code.speed, "", ...code.security, "",
    ...code.ecosystem, "", ...code.scalability, "",
    ...code.devExp,
  ];
}
